[build]
  functions = "netlify/functions"
  publish = "dist"

[[redirects]]
  from = "/.netlify/functions/*"
  to = "/.netlify/functions/:splat"
  status = 200 


[dev]
  functions = "netlify/functions"
  framework = "#custom"

[context.deploy-preview]
  [context.deploy-preview.environment]
    NETLIFY_EXPERIMENTAL_ENABLE_NEW_FORM_HANDLING = "true"