[build]
  functions = "netlify/functions"
  publish = "dist"

[[redirects]]
  from = "/.netlify/functions/*"
  to = "/.netlify/functions/:splat"
  status = 200

[dev]
  framework = "vite"
  targetPort = 5173
  port = 8888
  publish = "dist"
  functions = "netlify/functions" 