export const artists = [
  {
    name: "The 2 Johnnies",
    image: "/images/artists/The2Johnnies.webp",
    imageFallback: "/images/artists/The2Johnnies.jpg",
    website: "https://www.the2johnnies.ie/",
  },
  {
    name: "Kaiser Chiefs",
    image: "/images/artists/KaiserChiefs.webp",
    imageFallback: "/images/artists/KaiserChiefs.jpg",
    website: "https://www.kaiserchiefs.com/",
  },
  {
    name: "The Coronas",
    image: "/images/artists/TheCoronas.webp",
    imageFallback: "/images/artists/TheCoronas.jpg",
    website: "https://thecoronas.net/",
  },
  {
    name: "Derek Ryan",
    image: "/images/artists/DerekRyan.webp",
    imageFallback: "/images/artists/DerekRyan.jpg",
    website: "https://derekryanmusic.com/",
  },
  {
    name: "Nathan Carter",
    image: "/images/artists/NathanCarter.webp",
    imageFallback: "/images/artists/NathanCarter.jpg",
    website: "https://www.nathancartermusic.com/",
  },
  {
    name: "Boyzlife",
    image: "/images/artists/Boyzlife.webp",
    imageFallback: "/images/artists/Boyzlife.png",
    website: "https://www.facebook.com/BoyzlifeTour",
  },
  {
    name: "Mark McCabe",
    image: "/images/artists/MarkMcCabe.webp",
    imageFallback: "/images/artists/MarkMcCabe.jpg",
    website: "https://www.markmccabe.ie/",
  },
  {
    name: "B*Witched",
    image: "/images/artists/BWitched.webp",
    imageFallback: "/images/artists/BWitched.png",
    website: "https://bwitchedofficial.com/",
  },
  {
    name: "The Tumbling Paddies",
    image: "/images/artists/TumblingPaddies.webp",
    imageFallback: "/images/artists/TumblingPaddies.jpg",
    website: "https://thetumblingpaddiesofficial.com/",
  },
  {
    name: "The Whistlin Donkeys",
    image: "/images/artists/TheWhistlinDonkeys.webp",
    imageFallback: "/images/artists/TheWhistlinDonkeys.jpg",
    website: "https://www.facebook.com/thewhistlindonkeys/?locale=en_GB",
  },
  {
    name: "Hugo Duncan",
    image: "/images/artists/HugoDuncan.webp",
    imageFallback: "/images/artists/HugoDuncan.png",
    website: "https://en.wikipedia.org/wiki/Hugo_Duncan",
  },
  {
    name: "Colin Graham",
    image: "/images/artists/ColinGraham.webp",
    imageFallback: "/images/artists/ColinGraham.jpeg",
    website: "https://www.facebook.com/cmgmusic123/",
  },
  {
    name: "Roll With It",
    image: "/images/artists/RollWithIt.webp",
    imageFallback: "/images/artists/RollWithIt.jpg",
    website: "https://rollwithitband.wixsite.com/home",
  },
  {
    name: "Julian Simmons",
    image: "/images/artists/JulianSimmons.webp",
    imageFallback: "/images/artists/JulianSimmons.jpg",
    website: "https://www.instagram.com/juliansimmonsofficial/?hl=en",
  },
  {
    name: "Taylor NI",
    image: "/images/artists/TaylorNI.webp",
    imageFallback: "/images/artists/TaylorNI.jpeg",
    website: "https://www.facebook.com/events/111-ballymena-road-bt414-antrim-united-kingdom/taylor-ni-a-tribute-to-taylor-swift/1138776761144898/",
  },
  {
    name: "Ceol",
    image: "/images/artists/Ceol.webp",
    imageFallback: "/images/artists/Ceol.jpg",
    website: "https://www.ceolband.com/",
  },
  {
    name: "All Folk'd Up",
    image: "/images/artists/AllFolk_dUp.webp",
    imageFallback: "/images/artists/AllFolk_dUp.jpg",
    website: "https://www.allfolkdup.ie/",
  },
  {
    name: "Luke Combs UK",
    image: "/images/artists/LukeCombsUK.webp",
    imageFallback: "/images/artists/LukeCombsUK.jpg",
    website: "https://lukecombsuk.com/",
  },
  {
    name: "Allie Sherlock",
    image: "/images/artists/AllieSherlock.webp",
    imageFallback: "/images/artists/AllieSherlock.jpeg",
    website: "https://www.alliesherlock.com/",
  },
  {
    name: "Clodagh Lawlor",
    image: "/images/artists/ClodaghLawlor.webp",
    imageFallback: "/images/artists/ClodaghLawlor.jpg",
    website: "https://www.clodaghlawlormusic.com/",
  },
  {
    name: "David James",
    image: "/images/artists/DavidJames.webp",
    imageFallback: "/images/artists/DavidJames.jpg",
    website: "https://davidjamesmusic.co.uk/",
  },
  {
    name: "Mike Denver",
    image: "/images/artists/MikeDenver.webp",
    imageFallback: "/images/artists/MikeDenver.jpg",
    website: "https://www.mikedenvermusic.com/",
  },
  {
    name: "Olivia Douglas",
    image: "/images/artists/OliviaDouglas.webp",
    imageFallback: "/images/artists/OliviaDouglas.png",
    website: "https://www.oliviadouglasmusic.com/",
  },
  {
    name: "Robert Mizzell",
    image: "/images/artists/RobertMizzell.webp",
    imageFallback: "/images/artists/RobertMizzell.jpg",
    website: "https://robertmizzell.ie/",
  },
  {
    name: "Claudia Buckley",
    image: "/images/artists/ClaudiaBuckley.webp",
    imageFallback: "/images/artists/ClaudiaBuckley.jpg",
    website: "https://www.youtube.com/channel/UCU8qlz5-2MeehDCnlDheGqA/about",
  },
  {
    name: "Jimmy Buckley",
    image: "/images/artists/JimmyBuckley.webp",
    imageFallback: "/images/artists/JimmyBuckley.jpg",
    website: "https://www.jimmy-buckley.com/",
  },
    {
    name: "Cliona Hagan",
    image: "/images/artists/ClionaHagan.jpg",
    imageFallback: "/images/artists/ClionaHagan.jpg",
    website: "https://www.clionahagan.com/",
  },
  {
    name: "Johnny Brady",
    image: "/images/artists/JohnnyBrady.webp",
    imageFallback: "/images/artists/JohnnyBrady.jpg",
    website: "https://johnny-brady.com/",
  },
  {
    name: "Folk That Rock",
    image: "/images/artists/FolkThatRock.webp",
    imageFallback: "/images/artists/FolkThatRock.jpg",
    website: "",
  },
  {
    name: "Stuart Banford",
    image: "/images/artists/StuartBanford.webp",
    imageFallback: "/images/artists/StuartBanford.jpeg",
    website: "https://www.facebook.com/stuart.banford/?locale=en_GB",
  },
  {
    name: "Garth Brooks Experience",
    image: "/images/artists/GarthBrooksExperience.webp",
    imageFallback: "/images/artists/GarthBrooksExperience.jpg",
    website: "https://www.garthbrookstribute.co.uk/",
  },
  {
    name: "Chris Armstrong",
    image: "/images/artists/ChrisArmstrong.webp",
    imageFallback: "/images/artists/ChrisArmstrong.jpg",
    website: "https://djchrisarmstrong.com/",
  },
  {
    name: "Shrek Rave",
    image: "/images/artists/ShrekTheRave.webp",
    imageFallback: "/images/artists/ShrekTheRave.jpg",
    website: "https://www.shrekraveofficial.com/",
  },
  {
    name: "The 30+ Club",
    image: "/images/artists/The30Club.webp",
    imageFallback: "/images/artists/The30Club.jpg",
    website: "https://the30plus.club/",
  },
  {
    name: "Sheep Shearing Disco",
    image: "/images/artists/SheepShearingDisco.webp",
    imageFallback: "/images/artists/SheepShearingDisco.jpg",
    website: "",
  },
  {
    name: "Bangerthon",
    image: "/images/artists/Bangerthon.webp",
    imageFallback: "/images/artists/Bangerthon.jpg",
    website: "",
  },
  {
    name: "Bingo Loco",
    image: "/images/artists/BingoLoco.webp",
    imageFallback: "/images/artists/BingoLoco.jpg",
    website: "https://www.bingoloco.com/",
  },
  {
    name: "And Many More...",
    image: "/images/bg4.jpg",
    imageFallback: "/images/bg4.jpg",
    website: "",
  },
];
  